language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 73d00ef3-0d34-4d62-956a-cffc12e3f61c
  app: backendpalettelit
  skip_cleanup: true
