language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 0sfGBXOWL2YCmiafuaflRE8eYUJ1iWPP3tj6ctm98oN59z+OY15C1iKwk3oOgygudzVFk0Yep4SO/1ekErzIIjjBAEyGMYpxxPxMgcAXO6AXNT73P/jksU9r9Ity4MXSMn1HuuV0de3BUWT7tVy7ho8twyk5X5fBAPdW7Hv6GzDkYRrzGDJIEYjXQG1TNC0PZ5y3UZ7T7X1E4W3fQUUWyQ7rCTMv92y2QcJuKAimjIFI34NEuN6elEA6jehy3lurhyST8xRfPirFgfyomewC7miMnPzAguXGhLFkHpmeVZdlFSWLfNHvRxjTy0R7Hq3HfvRh5mOY8FtBcUGxxyIy30579VKuaqYFikJHSiagI+OZixaavvBTlXg9tzJ3c9ZVs40c6300nNVaQ0RrIHTZ3LD9DAVNtZllIjLYOjKW8e8vzA2Ch+huTGwphpvRc2rTxxsflM8L6E5LBV2FiFD2ZbNXmb774Ahk0H/MNiThCj+cuez7hjEjyUk+f4EZhDeMRnm2M2osDv1IIEn5hYefCT/8SK/v8JIsSYWLbfDS1bBX5IrO65xdh6J/Z74UfPf+Eb+MWeblH4xoZ18MQRM7pySmE6+FYWDHUnFGAz/Qlebt1ZTELGEObk2jKpvr9pBpQXe8eTZSyAJxR+qoiVbOAmbMVQ3bse5fAOQVZNCMIdQ=
  app: backendpalettelit
  skip_cleanup: true